name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 0 * * *' # 06:00 IST

jobs:
  ci:
    name: CI (${{ matrix.nixSystem }})
    # https://github.com/actions/partner-runner-images/tree/main/images
    runs-on: ${{ matrix.nixSystem == 'x86_64-linux' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        nixSystem: [ aarch64-linux, x86_64-linux, ]
    steps:
      - run: TZ='Asia/Kolkata' date +'%Y/%m/%d %H:%M:%S'
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run github:nixos/nixpkgs?ref=nixos-unstable#cargo -- build
      - run: nix run github:nixos/nixpkgs?ref=nixos-unstable#cargo -- test
      - run: nix run github:nixos/nixpkgs?ref=nixos-unstable#cargo -- clippy -- --deny warnings
